### ISSUE TITLE
This is no longer 100% multimc, so do not call it multimc (refer to about page)

### ISSUE THREAD

**Issue by kb-1000** [JJTech0130/MultiMC5#29]
People show up in the discord asking why 1.16 is not there (even though it is with the official build), and it turns out they were using your build. Rename it and change/remove the discord links. Also please change the "Report a Bug" link. I'm not sure if you'll need to change or delete the Reddit link tho

**Comment by JJTech0130** [comment]
The code in this repo is actually the same as the official one except for a few changes like the meta repo link, and the reason 1.16 is not there is that I have not had time to add it to the meta repo, and I don't understand the automated python scripts yet. I am working on that tho so 1.16 should work in the near future. I will try to change the report a bug links. I have some other priorities right now so that might take a little bit

**Comment by JJTech0130** [comment]
I think the best course of action (for now) is to simply add an option to the cmake to allow alternate meta URL's and then add an option to the meta script to use arm LWJGL.

**Comment by kb-1000** [comment]
It's not the task of the MultiMC community to support your custom fork with custom problems. Do that yourself. That's waht I'm requesting here. Also, it's not the same. If it was the same, it would behave exactly the same.

**Comment by JJTech0130** [comment]
If https://github.com/MultiMC/MultiMC5/pull/3234 gets merged, this will be the exact same.

**Comment by kb-1000** [comment]
MultiMC#3234 would only make this issue worse.

**Comment by JJTech0130** [comment]
My goal eventually is to get it into a state that there can be official ARM releases. There are 3 options I see that would be viable for this.
1. Use separate main repos for the arm and regular version
2. Use the same main repo with build flags and a separate meta repo
3. Have MultiMC correctly detect ARM architectures and feed different libs (from the same meta repo) to the instance being launched.

The first option is ok for the short term, but I don’t want to have to keep updating this forever. The second option could work, and that is what https://github.com/MultiMC/MultiMC5/pull/3234 is for. The third option would require a lot of work, but it could be done.

I don’t want this to become a separate thing, I would like it to become official.

**Comment by JJTech0130** [comment]
Would it be enough to do something like this:
![574B44E6-6F8E-4074-AA3F-26718EA052E7](https://user-images.githubusercontent.com/53275876/98016680-44d0ca80-1dcc-11eb-9562-a98d8c7dfabe.png)

Just adding an notice and renaming the git repo?

This repo does not have any commits -it is only built differently- however, I can see that it may be an issue because of the modified meta repo.

**Comment by kb-1000** [comment]
That's... a bad comparision. That should be taken down completely, for being a cracked minecraft launcher.

**Comment by JJTech0130** [comment]
Yeah. Couldn't find very many active forks 😉.

**Comment by JJTech0130** [comment]
Back to the point.

Do I have to remove *all* references to the MultiMC name in *all* of the code, as well as support links?
If so, it will be very hard to provide automated builds. Although, some kind of find-and-replace might work.

How does this pertain to unmodified source code? Should I just create a separate repo, with a GH-Pages site, just to post manual builds & instructions?

**Comment by JJTech0130** [comment]
My build server decided not to work... I need to get that fixed 😄

**Comment by JJTech0130** [comment]
I am starting to work on removing refs to the official MultiMC. See the custom branch.
